# Generated by Django 5.2.7 on 2025-10-12 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام واحد/دپارتمان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'واحد',
                'verbose_name_plural': 'واحدها',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=50, unique=True, verbose_name='شماره درخواست')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('admin_pending', 'در انتظار مسئول اداری'), ('factory_pending', 'در انتظار مدیر کارخانه'), ('management_pending', 'در انتظار مدیریت'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('admin_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید مسئول اداری')),
                ('factory_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید مدیر کارخانه')),
                ('management_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید مدیریت')),
                ('admin_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_requests_admin_approved', to=settings.AUTH_USER_MODEL, verbose_name='تأیید کننده مسئول اداری')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overtime_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('factory_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_requests_factory_approved', to=settings.AUTH_USER_MODEL, verbose_name='تأیید کننده مدیر کارخانه')),
                ('management_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_requests_management_approved', to=settings.AUTH_USER_MODEL, verbose_name='تأیید کننده مدیریت')),
            ],
            options={
                'verbose_name': 'درخواست اضافه کاری',
                'verbose_name_plural': 'درخواست\u200cهای اضافه کاری',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OvertimeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200, verbose_name='نام پرسنل')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('reason', models.TextField(verbose_name='علت اضافه کاری')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='overtime.department', verbose_name='واحد')),
                ('overtime_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='overtime.overtimerequest', verbose_name='درخواست اضافه کاری')),
            ],
            options={
                'verbose_name': 'آیتم اضافه کاری',
                'verbose_name_plural': 'آیتم\u200cهای اضافه کاری',
            },
        ),
    ]
