# Generated by Django 5.2.7 on 2025-10-13 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerequest',
            name='cancel_reason',
            field=models.TextField(blank=True, verbose_name='دلیل لغو'),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو'),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_requests_canceled', to=settings.AUTH_USER_MODEL, verbose_name='لغو کننده'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='status',
            field=models.CharField(choices=[('admin_pending', 'در انتظار مسئول اداری'), ('factory_pending', 'در انتظار مدیر کارخانه'), ('management_pending', 'در انتظار مدیریت'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('canceled', 'لغو شده')], default='admin_pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
