# Generated by Django 5.2.7 on 2025-10-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('management', 'مدیریت'), ('sales_manager', 'مدیر فروش'), ('finance_manager', 'مدیر مالی'), ('factory_manager', 'مدیر کارخانه'), ('factory_planner', 'برنامه\u200cریز کارخانه')], default='management', max_length=32),
        ),
    ]
