# Generated by Django 5.2.7 on 2025-10-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('management', 'مدیریت'), ('sales_manager', 'مدیر فروش'), ('finance_manager', 'مدیر مالی'), ('factory_planner', 'واحد برنامه\u200cریزی'), ('factory_manager', 'مدیر کارخانه'), ('administrative_officer', 'مسئول اداری')], default='management', max_length=32),
        ),
    ]
