# Generated by Django 5.2.7 on 2025-10-22 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_unit_options'),
        ('planning', '0002_alter_productionitem_packaging_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionitem',
            name='packaging_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.packagingtype', verbose_name='نوع بسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='productionitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.unit', verbose_name='واحد'),
        ),
    ]
