# Generated by Django 5.2.7 on 2025-10-12 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='مرکز هزینه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'مرکز هزینه',
                'verbose_name_plural': 'مراکز هزینه',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع درخواست')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'نوع درخواست',
                'verbose_name_plural': 'انواع درخواست',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('creator_approved', 'تایید درخواست\u200cکننده'), ('factory_approved', 'تایید مدیر کارخانه'), ('management_approved', 'تایید مدیر اصلی'), ('canceled', 'لغو شده')], default='draft', max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('creator_approved_at', models.DateTimeField(blank=True, null=True)),
                ('factory_approved_at', models.DateTimeField(blank=True, null=True)),
                ('management_approved_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_requests', to=settings.AUTH_USER_MODEL)),
                ('creator_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests_creator', to=settings.AUTH_USER_MODEL)),
                ('factory_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests_factory', to=settings.AUTH_USER_MODEL)),
                ('management_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests_management', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='requests.costcenter', verbose_name='مرکز هزینه')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='requests.request')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='requests.requesttype', verbose_name='نوع درخواست')),
            ],
        ),
    ]
