# Generated by Django 5.2.7 on 2025-10-11 15:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام مشتری')),
                ('phone', models.CharField(max_length=50, verbose_name='شماره تماس مشتری')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('customer_code', models.CharField(max_length=50, unique=True, verbose_name='کد مشتری')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.CreateModel(
            name='PackagingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نوع بسته\u200cبندی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'نوع بسته\u200cبندی',
                'verbose_name_plural': 'انواع بسته\u200cبندی',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد محصول')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع درخواست')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'نوع درخواست',
                'verbose_name_plural': 'انواع درخواست',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='روش ارسال')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'روش ارسال',
                'verbose_name_plural': 'روش\u200cهای ارسال',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='واحد اندازه\u200cگیری')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'واحد',
                'verbose_name_plural': 'واحدها',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('sales_approved', 'تایید فروش'), ('finance_approved', 'تایید مالی'), ('management_approved', 'تایید مدیریت'), ('canceled', 'لغو شده')], default='draft', max_length=32)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('official_type', models.CharField(choices=[('official', 'رسمی'), ('informal', 'غیر رسمی')], default='official', max_length=10, verbose_name='نوع رسمیت')),
                ('customer_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد مشتری')),
                ('customer_name', models.CharField(max_length=200, verbose_name='نام مشتری')),
                ('customer_phone', models.CharField(max_length=50, verbose_name='شماره تماس مشتری')),
                ('recipient_address', models.TextField(verbose_name='آدرس گیرنده')),
                ('order_notes', models.TextField(blank=True, verbose_name='توضیحات کلی سفارش')),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('sales_approved_at', models.DateTimeField(blank=True, null=True)),
                ('finance_approved_at', models.DateTimeField(blank=True, null=True)),
                ('management_approved_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_canceled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_created', to=settings.AUTH_USER_MODEL)),
                ('finance_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_finance_approved', to=settings.AUTH_USER_MODEL)),
                ('management_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_management_approved', to=settings.AUTH_USER_MODEL)),
                ('sales_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_sales_approved', to=settings.AUTH_USER_MODEL)),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.requesttype', verbose_name='نوع درخواست')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد محصول')),
                ('product_name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=12, verbose_name='مقدار')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='شماره بچ')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='توضیحات')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.customerorder')),
                ('packaging_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.packagingtype', verbose_name='نوع بسته\u200cبندی')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.product', verbose_name='محصول')),
                ('shipping_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.shippingmethod', verbose_name='روش ارسال')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.unit', verbose_name='واحد')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
