# Generated by Django 5.2.7 on 2025-10-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'واحد', 'verbose_name_plural': 'واحد اندازه گیری'},
        ),
    ]
